spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://10.50.26.144:5432/booking-be?timezone=Asia/Ho_Chi_Minh}
  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    jwt:
      expiration-time: 86400000
      key: ${JWT_KEY}
      issuer: ${JWT_ISSUER}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: true
    open-in-view: false
  application:
    name: nike-be
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${MAIL_USERNAME}
  data:
    redis:
      host: ${REDIS_SERVICE_HOST}
      port: ${REDIS_SERVICE_PORT}
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method
    config-url: "/api/v3/api-docs/swagger-config"
    url: "/api/v3/api-docs"
  api-docs:
    enabled: true
    path: "/v3/api-docs"
server:
  port: 8080
  servlet:
    context-path: /api
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        security: DEBUG
    com:
      example:
        controller: DEBUG
        service: DEBUG
        repository: DEBUG
